[package]
name = "nightcycle/index-util"
description = "some handy utilities for finding instances"
version = "3.0.0"
license = "Apache"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]


[dependencies]
TypeUnionLib = "nightcycle/type-union-lib@^0.2"
